import {createAction} from "redux-actions";
export const loginRequest = createAction('LOGIN_REQUEST');
export const loginRequestSuccess = createAction('LOGIN_REQUEST_SUCCESS');
export const registerRequest = createAction('REGISTER_REQUEST');
export const registerRequestSuccess = createAction('REGISTER_REQUEST_SUCCESS');
export const logoutRequest = createAction('LOGOUT_REQUEST');
export const logoutRequestSuccess = createAction('LOGOUT_REQUEST_SUCCESS');
export const refreshTokensRequest = createAction('REFRESH_TOKENS_REQUEST');
export const refreshTokensRequestSuccess = createAction('REFRESH_TOKENS_REQUEST_SUCCESS');
export const updateUserRequest = createAction('UPDATE_USER_REQUEST');
export const updateUserRequestSuccess = createAction('UPDATE_USER_REQUEST_SUCCESS');
export const deleteUserRequest = createAction('DELETE_USER_REQUEST');
export const deleteUserRequestSuccess = createAction('DELETE_USER_REQUEST_SUCCESS');
export const enqueueSnackbarInfo = createAction('ENQUEUE_SNACKBAR_INFO');
export const enqueueSnackbarSuccess = createAction('ENQUEUE_SNACKBAR_SUCCESS');
export const enqueueSnackbarError = createAction('ENQUEUE_SNACKBAR_ERROR');
export const removeSnackbar = createAction('REMOVE_SNACKBAR');