// <auto-generated />
using System;
using Kvikmynd.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kvikmynd.Infrastructure.Migrations
{
    [DbContext(typeof(KvikmyndDbContext))]
    [Migration("20220310201902_AddedNewSeedingData")]
    partial class AddedNewSeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kvikmynd.Domain.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "anime"
                        },
                        new
                        {
                            Id = 2,
                            Name = "biography"
                        },
                        new
                        {
                            Id = 3,
                            Name = "western"
                        },
                        new
                        {
                            Id = 4,
                            Name = "military"
                        },
                        new
                        {
                            Id = 5,
                            Name = "detective"
                        },
                        new
                        {
                            Id = 6,
                            Name = "child"
                        },
                        new
                        {
                            Id = 7,
                            Name = "for adults"
                        },
                        new
                        {
                            Id = 8,
                            Name = "documentary"
                        },
                        new
                        {
                            Id = 9,
                            Name = "drama"
                        },
                        new
                        {
                            Id = 10,
                            Name = "the game"
                        },
                        new
                        {
                            Id = 11,
                            Name = "history"
                        },
                        new
                        {
                            Id = 12,
                            Name = "comedy"
                        },
                        new
                        {
                            Id = 13,
                            Name = "concert"
                        },
                        new
                        {
                            Id = 14,
                            Name = "short film"
                        },
                        new
                        {
                            Id = 15,
                            Name = "crime"
                        },
                        new
                        {
                            Id = 16,
                            Name = "melodrama"
                        },
                        new
                        {
                            Id = 17,
                            Name = "music"
                        },
                        new
                        {
                            Id = 18,
                            Name = "cartoon"
                        },
                        new
                        {
                            Id = 19,
                            Name = "musical"
                        },
                        new
                        {
                            Id = 20,
                            Name = "news"
                        },
                        new
                        {
                            Id = 21,
                            Name = "adventures"
                        },
                        new
                        {
                            Id = 22,
                            Name = "real tv"
                        },
                        new
                        {
                            Id = 23,
                            Name = "family"
                        },
                        new
                        {
                            Id = 24,
                            Name = "sport"
                        },
                        new
                        {
                            Id = 25,
                            Name = "talk show"
                        },
                        new
                        {
                            Id = 26,
                            Name = "thriller"
                        },
                        new
                        {
                            Id = 27,
                            Name = "horrors"
                        },
                        new
                        {
                            Id = 28,
                            Name = "fantastic"
                        },
                        new
                        {
                            Id = 29,
                            Name = "film noir"
                        },
                        new
                        {
                            Id = 30,
                            Name = "fantasy"
                        },
                        new
                        {
                            Id = 31,
                            Name = "action"
                        });
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.GenreMovie", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("GenreMovie");

                    b.HasData(
                        new
                        {
                            GenreId = 9,
                            MovieId = 1
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 1
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 2
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 2
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 2
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 3
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 3
                        },
                        new
                        {
                            GenreId = 5,
                            MovieId = 4
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 4
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 4
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 4
                        },
                        new
                        {
                            GenreId = 21,
                            MovieId = 5
                        },
                        new
                        {
                            GenreId = 28,
                            MovieId = 5
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 6
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 6
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 6
                        },
                        new
                        {
                            GenreId = 27,
                            MovieId = 7
                        },
                        new
                        {
                            GenreId = 28,
                            MovieId = 7
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 7
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 7
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 8
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 8
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 8
                        },
                        new
                        {
                            GenreId = 5,
                            MovieId = 8
                        },
                        new
                        {
                            GenreId = 4,
                            MovieId = 9
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 9
                        },
                        new
                        {
                            GenreId = 11,
                            MovieId = 9
                        },
                        new
                        {
                            GenreId = 31,
                            MovieId = 10
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 10
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 10
                        },
                        new
                        {
                            GenreId = 12,
                            MovieId = 10
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 10
                        },
                        new
                        {
                            GenreId = 5,
                            MovieId = 10
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 11
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 11
                        },
                        new
                        {
                            GenreId = 31,
                            MovieId = 12
                        },
                        new
                        {
                            GenreId = 28,
                            MovieId = 12
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 13
                        },
                        new
                        {
                            GenreId = 2,
                            MovieId = 13
                        },
                        new
                        {
                            GenreId = 12,
                            MovieId = 13
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 14
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 14
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 14
                        },
                        new
                        {
                            GenreId = 5,
                            MovieId = 14
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 15
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 15
                        },
                        new
                        {
                            GenreId = 27,
                            MovieId = 15
                        },
                        new
                        {
                            GenreId = 5,
                            MovieId = 15
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 16
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 16
                        },
                        new
                        {
                            GenreId = 5,
                            MovieId = 16
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 17
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 18
                        },
                        new
                        {
                            GenreId = 31,
                            MovieId = 19
                        },
                        new
                        {
                            GenreId = 12,
                            MovieId = 19
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 19
                        },
                        new
                        {
                            GenreId = 28,
                            MovieId = 20
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 20
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 20
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 20
                        },
                        new
                        {
                            GenreId = 5,
                            MovieId = 20
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 21
                        },
                        new
                        {
                            GenreId = 26,
                            MovieId = 22
                        },
                        new
                        {
                            GenreId = 9,
                            MovieId = 22
                        },
                        new
                        {
                            GenreId = 15,
                            MovieId = 22
                        },
                        new
                        {
                            GenreId = 27,
                            MovieId = 23
                        },
                        new
                        {
                            GenreId = 28,
                            MovieId = 23
                        },
                        new
                        {
                            GenreId = 8,
                            MovieId = 23
                        });
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Cover")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("YoutubeLink")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cover = new byte[0],
                            Description = "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power.",
                            Title = "Fight Club",
                            YoutubeLink = "SUXWAEX2jlg"
                        },
                        new
                        {
                            Id = 2,
                            Cover = new byte[0],
                            Description = "It's the late 1980s. Twenty-seven year old Wall Streeter Patrick Bateman travels among a closed network of the proverbial beautiful people, that closed network in only they able to allow others like themselves in in a feeling of superiority. Patrick has a routinized morning regimen to maintain his appearance of attractiveness and fitness. He, like those in his network, are vain, narcissistic, egomaniacal and competitive, always having to one up everyone else in that presentation of oneself, but he, unlike the others, realizes that, for himself, all of these are masks to hide what is truly underneath, someone/something inhuman in nature. In other words, he is comprised of a shell resembling a human that contains only greed and disgust, greed in wanting what others may have, and disgust for those who do not meet his expectations and for himself in not being the first or the best. That disgust ends up manifesting itself in wanting to rid the world of those people, he not seeing them as people but only of those characteristics he wants to rid.",
                            Title = "American Psycho",
                            YoutubeLink = "5YnGhW4UEhc"
                        },
                        new
                        {
                            Id = 3,
                            Cover = new byte[0],
                            Description = "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
                            Title = "Pulp Fiction",
                            YoutubeLink = "s7EdQ4FqbhY"
                        },
                        new
                        {
                            Id = 4,
                            Cover = new byte[0],
                            Description = "Memento chronicles two separate stories of Leonard, an ex-insurance investigator who can no longer build new memories, as he attempts to find the murderer of his wife, which is the last thing he remembers. One story line moves forward in time while the other tells the story backwards revealing more each time.",
                            Title = "Memento",
                            YoutubeLink = "HDWylEQSwFo"
                        },
                        new
                        {
                            Id = 5,
                            Cover = new byte[0],
                            Description = "\"2001\" is a story of evolution. Sometime in the distant past, someone or something nudged evolution by placing a monolith on Earth (presumably elsewhere throughout the universe as well). Evolution then enabled humankind to reach the moon's surface, where yet another monolith is found, one that signals the monolith placers that humankind has evolved that far. Now a race begins between computers (HAL) and human (Bowman) to reach the monolith placers. The winner will achieve the next step in evolution, whatever that may be.",
                            Title = "2001: A Space Odyssey",
                            YoutubeLink = "oR_e9y-bka0"
                        },
                        new
                        {
                            Id = 6,
                            Cover = new byte[0],
                            Description = "In rural Texas, welder and hunter Llewelyn Moss (Josh Brolin) discovers the remains of several drug runners who have all killed each other in an exchange gone violently wrong. Rather than report the discovery to the police, Moss decides to simply take the two million dollars present for himself. This puts the psychopathic killer, Anton Chigurh (Javier Bardem), on his trail as he dispassionately murders nearly every rival, bystander and even employer in his pursuit of his quarry and the money. As Moss desperately attempts to keep one step ahead, the blood from this hunt begins to flow behind him with relentlessly growing intensity as Chigurh closes in. Meanwhile, the laconic Sheriff Ed Tom Bell (Tommy Lee Jones) blithely oversees the investigation even as he struggles to face the sheer enormity of the crimes he is attempting to thwart.",
                            Title = "No Country for Old Men",
                            YoutubeLink = "38A__WT3-o0"
                        },
                        new
                        {
                            Id = 7,
                            Cover = new byte[0],
                            Description = "Animal activists invade a laboratory with the intention of releasing chimpanzees that are undergoing experimentation, infected by a virus -a virus that causes rage. The naive activists ignore the pleas of a scientist to keep the cages locked, with disastrous results. Twenty-eight days later, our protagonist, Jim, wakes up from a coma, alone, in an abandoned hospital. He begins to seek out anyone else to find London is deserted, apparently without a living soul. After finding a church, which had become inhabited by zombie like humans intent on his demise, he runs for his life. Selena and Mark rescue him from the horde and bring him up to date on the mass carnage and horror as all of London tore itself apart. This is a tale of survival and ultimately, heroics, with nice subtext about mankind's savage nature.",
                            Title = "28 Days Later",
                            YoutubeLink = "v=c7ynwAgQlDQ"
                        },
                        new
                        {
                            Id = 8,
                            Cover = new byte[0],
                            Description = "Forty years ago, Harriet Vanger disappeared from a family gathering on the island owned and inhabited by the powerful Vanger clan. Her body was never found, yet her uncle suspects murder and that the killer is a member of his own tightly knit but dysfunctional family. He employs disgraced financial journalist Mikael Blomkvist and the tattooed, ruthless computer hacker Lisbeth Salander to investigate. When the pair link Harriet's disappearance to a number of grotesque murders from almost forty years ago, they begin to unravel a dark and appalling family history; but, the Vangers are a secretive clan, and Blomkvist and Salander are about to find out just how far they are prepared to go to protect themselves.",
                            Title = "The Girl with the Dragon Tattoo",
                            YoutubeLink = "gBVwUWeB0CE"
                        },
                        new
                        {
                            Id = 9,
                            Cover = new byte[0],
                            Description = "May/June 1940. Four hundred thousand British and French soldiers are hole up in the French port town of Dunkirk. The only way out is via sea, and the Germans have air superiority, bombing the British soldiers and ships without much opposition. The situation looks dire and, in desperation, Britain sends civilian boats in addition to its hard-pressed Navy to try to evacuate the beleaguered forces. This is that story, seen through the eyes of a soldier amongst those trapped forces, two Royal Air Force fighter pilots, and a group of civilians on their boat, part of the evacuation fleet.",
                            Title = "Dunkirk",
                            YoutubeLink = "F-eMt3SrfFU"
                        },
                        new
                        {
                            Id = 10,
                            Cover = new byte[0],
                            Description = "The movie opens in a Los Angeles convenience store one late Monday night, where a smalltime drug dealer named Nick (Aaron Eckhart) is trying to decide what coffee brand to buy. His ex-lover Dallas (Paulina Porizkova) and fellow hitman Billy Hill (James LeGros) are getting impatient and tell him to hurry up. Conflicts between Nick and the cashier (Luck Hari) ensue, resulting in Dallas shooting the cashier dead. Though the three attempt to cover up the crime, they are forced to also shoot a police officer (Bari K. Willerford) when he discovers blood on the ground.",
                            Title = "Thursday",
                            YoutubeLink = "LJ0lN6yLrrg"
                        },
                        new
                        {
                            Id = 11,
                            Cover = new byte[0],
                            Description = "Tony Montana manages to leave Cuba during the Mariel exodus of 1980. He finds himself in a Florida refugee camp but his friend Manny has a way out for them: undertake a contract killing and arrangements will be made to get a green card. He's soon working for drug dealer Frank Lopez and shows his mettle when a deal with Colombian drug dealers goes bad. He also brings a new level of violence to Miami. Tony is protective of his younger sister but his mother knows what he does for a living and disowns him. Tony is impatient and wants it all however, including Frank's empire and his mistress Elvira Hancock. Once at the top however, Tony's outrageous actions make him a target and everything comes crumbling down.",
                            Title = "Scarface",
                            YoutubeLink = "7pQQHnqBa2E"
                        },
                        new
                        {
                            Id = 12,
                            Cover = new byte[0],
                            Description = "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. As a rebel against the machines, Neo must confront the agents: super-powerful computer programs devoted to stopping Neo and the entire human rebellion.",
                            Title = "The Matrix",
                            YoutubeLink = "vKQi3bBA1y8&t=2s"
                        },
                        new
                        {
                            Id = 13,
                            Cover = new byte[0],
                            Description = "A true story about Frank Abagnale Jr. who, before his 19th birthday, successfully conned millions of dollars worth of checks as a Pan Am pilot, doctor, and legal prosecutor. An FBI agent makes it his mission to put him behind bars. But Frank not only eludes capture, he revels in the pursuit.",
                            Title = "Catch Me If You Can",
                            YoutubeLink = "s-7pyIxz8Qg"
                        },
                        new
                        {
                            Id = 14,
                            Cover = new byte[0],
                            Description = "A film about two homicide detectives' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic John Doe (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer's terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer's modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer.",
                            Title = "Se7en",
                            YoutubeLink = "znmZoVkCjpI"
                        },
                        new
                        {
                            Id = 15,
                            Cover = new byte[0],
                            Description = "Haunted by a persistent writer's block, the aspiring author and recovering alcoholic, Jack Torrance, drags his wife, Wendy, and his gifted son, Danny, up snow-capped Colorado's secluded Overlook Hotel after taking up a job as an off-season caretaker. As the cavernous hotel shuts down for the season, the manager gives Jack a grand tour, and the facility's chef, the ageing Mr Hallorann, has a fascinating chat with Danny about a rare psychic gift called 'The Shining', making sure to warn him about the hotel's abandoned rooms, and, in particular, the off-limits Room 237. However, instead of overcoming the dismal creative rut, little by little, Jack starts losing his mind, trapped in an unforgiving environment of seemingly endless snowstorms, and a gargantuan silent prison riddled with strange occurrences and eerie visions. Now, the incessant voices inside Jack's head demand sacrifice. Is Jack capable of murder?",
                            Title = "The Shining",
                            YoutubeLink = "S014oGZiSdI"
                        },
                        new
                        {
                            Id = 16,
                            Cover = new byte[0],
                            Description = "The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, AND each other. Based on the play, all of the action takes place on the stage of the jury room.",
                            Title = "12 Angry Men",
                            YoutubeLink = "13J_9B5jEk"
                        },
                        new
                        {
                            Id = 17,
                            Cover = new byte[0],
                            Description = "Derek Vineyard is paroled after serving 3 years in prison for brutally killing two black men who tried to break into/steal his truck. Through his brother's, Danny Vineyard, narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
                            Title = "American History X",
                            YoutubeLink = "XfQYHqsiN5g"
                        },
                        new
                        {
                            Id = 18,
                            Cover = new byte[0],
                            Description = "McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse.",
                            Title = "One Flew Over the Cuckoo's Nest",
                            YoutubeLink = "OXrcDonY-B8"
                        },
                        new
                        {
                            Id = 19,
                            Cover = new byte[0],
                            Description = "Four Jack-the-lads find themselves heavily - seriously heavily - in debt to an East End hard man and his enforcers after a crooked card game. Overhearing their neighbours in the next flat plotting to hold up a group of out-of-their-depth drug growers, our heroes decide to stitch up the robbers in turn. In a way the confusion really starts when a pair of antique double-barrelled shotguns go missing in a completely different scam.",
                            Title = "Lock, Stock and Two Smoking Barrels",
                            YoutubeLink = "h6hZkvrFIj0"
                        },
                        new
                        {
                            Id = 20,
                            Cover = new byte[0],
                            Description = "Benjamin is invisible, a nobody. This changes abruptly when he meets charismatic Max. Even though they couldn't seem more different from the outside, they share the same interest: hacking. Together with Max's friends, the impulsive Stephan and paranoid Paul, they form the subversive Hacker collective CLAY (CLOWNS LAUGHING @ YOU). CLAY provokes with fun campaigns and speaks for a whole generation. For the first time in his life, Benjamin is part of something and even the attractive Marie begins noticing him. But fun turns into deadly danger when CLAY appears on the BKA's (Bundeskriminalamt, Federal Criminal Police Office) as well as Europol's most wanted list. Hunted by Cybercrime investigator Hanne Lindberg, Benjamin is no longer a nobody, but instead one of the most wanted hackers in the world.",
                            Title = "Who Am I",
                            YoutubeLink = "ynW6Ys3LLAQ"
                        },
                        new
                        {
                            Id = 21,
                            Cover = new byte[0],
                            Description = "The intersecting life stories of Daniel Plainview and Eli Sunday in early twentieth century California is presented. Miner turn oilman Daniel Plainview is a driven man who will do whatever it takes to achieve his goals. He works hard but he also takes advantage of those around him at their expense if need be. His business partner is his son H.W., who in reality he 'acquired' when H.W.'s biological single father, who worked on one of Daniel's rigs, got killed in a workplace accident. Daniel is deeply protective of H.W. if only for what H.W. brings to the partnership. Eli Sunday is one in a pair of twins, whose family farm Daniel purchases for the major oil deposit located on it. Eli, the local preacher and a self-proclaimed faith healer, wants the money from the sale of the property to finance his own church. The lives of the two competitive men often clash as Daniel pumps oil off the property and tries to acquire all the surrounding land at bargain prices to be able to build a pipeline to the coast, and as Eli tries to build his own religious empire.",
                            Title = "There Will Be Blood",
                            YoutubeLink = "FeSLPELpMeM"
                        },
                        new
                        {
                            Id = 22,
                            Cover = new byte[0],
                            Description = "Travis Bickle is an ex-Marine and Vietnam War veteran living in New York City. As he suffers from insomnia, he spends his time working as a taxi driver at night, watching porn movies at seedy cinemas during the day, or thinking about how the world, New York in particular, has deteriorated into a cesspool. He's a loner who has strong opinions about what is right and wrong with mankind. For him, the one bright spot in New York humanity is Betsy, a worker on the presidential nomination campaign of Senator Charles Palantine. He becomes obsessed with her. After an incident with her, he believes he has to do whatever he needs to make the world a better place in his opinion. One of his priorities is to be the savior for Iris, a twelve-year-old runaway and prostitute who he believes wants out of the profession and under the thumb of her pimp and lover Matthew.",
                            Title = "Taxi Driver",
                            YoutubeLink = "UUxD4-dEzn0"
                        },
                        new
                        {
                            Id = 23,
                            Cover = new byte[0],
                            Description = "A US research station, Antarctica, early-winter 1982. The base is suddenly buzzed by a helicopter from the nearby Norwegian research station. They are trying to kill a dog that has escaped from their base. After the destruction of the Norwegian chopper the members of the US team fly to the Norwegian base, only to discover them all dead or missing. They do find the remains of a strange creature the Norwegians burned. The Americans take it to their base and deduce that it is an alien life form. After a while it is apparent that the alien can take over and assimilate into other life forms, including humans, and can spread like a virus. This means that anyone at the base could be inhabited by The Thing, and tensions escalate.",
                            Title = "The Thing",
                            YoutubeLink = "5ftmr17M-a4"
                        });
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.MovieRating", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MovieRating");
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.Comment", b =>
                {
                    b.HasOne("Kvikmynd.Domain.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kvikmynd.Domain.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.GenreMovie", b =>
                {
                    b.HasOne("Kvikmynd.Domain.Models.Genre", "Genre")
                        .WithMany("GenreMovies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kvikmynd.Domain.Models.Movie", "Movie")
                        .WithMany("GenreMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.MovieRating", b =>
                {
                    b.HasOne("Kvikmynd.Domain.Models.Movie", "Movie")
                        .WithMany("MovieRatings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kvikmynd.Domain.Models.User", "User")
                        .WithMany("MovieRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.User", b =>
                {
                    b.OwnsMany("Kvikmynd.Domain.Models.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Kvikmynd.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Kvikmynd.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kvikmynd.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Kvikmynd.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.Genre", b =>
                {
                    b.Navigation("GenreMovies");
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.Movie", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("GenreMovies");

                    b.Navigation("MovieRatings");
                });

            modelBuilder.Entity("Kvikmynd.Domain.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("MovieRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
